sudo: false
language: node_js
node_js: stable
after_success:
  - |

       $(npm bin)/set-up-ssh --key "$encrypted_c726a34f4465_key" \
                             --iv "$encrypted_c726a34f4465_iv" \
                             --path-encrypted-key ".travis/github_deploy_key.enc"

       $(npm bin)/update-branch --commands "npm run build" \
                                --commit-message "Update Build [skip ci]" \
                                --directory "_book" \
                                --distribution-branch "gh-pages" \
                                --source-branch "master"